### ISSUE TITLE
API Limit response error

### ISSUE THREAD

**Issue by brod** [BlockIo/block_io-nodejs#9]
During testing, the API limit was exceeded - responses from block.io were not handled gracefully by `block_io`.

```
/node_modules/block_io/lib/block_io.js:245
    if (typeof(data) !== 'object' || data.status !== 'success') {
                                         ^

TypeError: Cannot read property 'status' of null
    at Request._callback (/node_modules/block_io/lib/block_io.js:245:42)
    at Request.self.callback (/node_modules/block_io/node_modules/request/request.js:368:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/node_modules/block_io/node_modules/request/request.js:1219:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/node_modules/block_io/node_modules/request/request.js:1167:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

AFAIK the response was in relation to API limit being exceeded, the purpose for exceeding the limit was developing response handlers.

**Comment by hitsnorth** [comment]
This is also a problem when the service is down.  Needs to be wrapped in error handling.

**Comment by terapi09** [comment]
bf8b1aa6af2b186b9ef10ab667f181f59f3d33c3
